print("digite dois números")
a = int(input("a="))
b = int(input("b="))
print("soma= ", a+b)
print("subtração= ", a-b)
print("multiplicação= ", a*b)
divComum=float(a/b)
print("divisão= ", divComum)
print("divisão truncada= ", a//b)
print("resto= ", a%b)
print("exponenciação= ", a**b)
